config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  namespace :user do
  	root :to => "impacts#index"
  end
  resources :impacts
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/footprint.rb
class Footprint < ApplicationRecord
	belongs_to :impact
	belongs_to :item
end

app/models/impact.rb
class Impact < ApplicationRecord
	belongs_to :user
	has_many :footprints
	has_many :items, :through => :footprints
	accepts_nested_attributes_for :items

	def api_calculate
		api_response = ImpactsHelper.api_test
		totals = 0

		items.each do |item|
		 	totals += quantity * item.value * api_response
		end

		return totals
	end
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
	has_many :footprints
	has_many :impacts, :through => :footprints
end

app/models/user.rb
class User < ApplicationRecord
  has_many :impacts
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
	  stored_location_for(resource) || impacts_path
	end
end

app/controllers/impacts_controller.rb
class ImpactsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index
		p current_user
		@impacts = current_user.impacts
	end

	def new
		@impact = Impact.new
	end

	def create
		p params
		current_user.impacts.create(impact_params)
		redirect_to impacts_path
	end

	private

	def impact_params
		params.require(:impact).permit(:name, :description, :quantity, :value, :item_ids => [])
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		current_user.items.create(item_params)
		redirect_to items_path
	end

	private

	def item_params
		params.require(:item).permit(:name, :value)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/impacts_helper.rb
module ImpactsHelper
	def self.api_test
		gallons = 50
		response = HTTParty.get("http://impact.brighterplanet.com/fuel_purchases.json?fuel_type=gasoline&timeframe=2019-01-01%2F2020-01-01&volume=#{gallons}&key=be471d8e-911c-4b49-aad3-631e500e5b19")
		gasdata = response.parsed_response
		carbon = gasdata["decisions"]["carbon"]["object"]["value"]
		@value = carbon/3
		p @value
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/impacts/index.html.erb
<div class="hero container">
	<div class="row">
		<div class="col-10">
			<!-- <h1>My Progress</h1>
			<p>You have <% @impacts.sum(:item) %> point(s).</p>
			<p>You need <%= 50000 - @impacts.sum(:item) %> more point(s) to save a tree!</p>
			<br>
			<br>
			 -->
			<h1>My Impacts</h1>
			<% @impacts.each do |impact| %>
			  <div>
			    <h3><%= impact.name %></h3>
		    	<% impact.items.each do |item| %>
		    		<p><%= item.name %></p>
		    		<p><%= item.value %></p>
		    	<% end %>
			    <% if impact.user.present? %>
			      <p><%= impact.user.email %></h3>
			    <% end %>
			 	<h2>Points: <%= impact.api_calculate.round %></h2>
			    <hr>
			    <br><br>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/impacts/new.html.erb
<div class="hero container">
	<div class="row">
		<div class="col-10">
			<h1>Add an Impact</h1>
			<%= simple_form_for @impact do |f| %>
		    <%= f.input :name %>
		    <%= f.input :quantity %>
		    <%= f.association :items %>
		    <%= f.submit 'Create', class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<div class="hero container">
	<div class="row">
		<div class="col-10">
			<h1>My Items</h1>
			<% @items.each do |item| %>
			  <div>
			    <h2><%= item.name %></h2>
			    <p><%= item.value %></p>
			    <hr>
			    <br><br>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/items/new.html.erb
<div class="hero container">
	<div class="row">
		<div class="col-10">
			<h1>Add an Item</h1>
			<%= simple_form_for @item do |f| %>
			    <%= f.input :name %>
			    <%= f.input :value %>
			    <%= f.submit 'Create', class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Save It</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800,800i,900,900i&display=swap" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-light" style="background-color: #18634c;">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#" id="logo"><em>save it</em></a>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'add an item', new_item_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'my items', items_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'add an impact', new_impact_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'my impacts', impacts_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="hero container">
	<div class="row">
		<div class="col-10">
			<h1>Making a difference starts here.</h1>
			<h2>Sign up now.</h2>
		</div>
	</div>
</div>